bugfix: fix qwen3.5 gdn precision issue with corrected chunk_gated_delta_rule_fwd_h implementation. (#1571)
Co-authored-by: hejun <hejun72@outlook.com>

diff --git a/xllm/compiler/tilelang/patches/tilelang_ascend/0001-install-ascend.patch b/xllm/compiler/tilelang/patches/tilelang_ascend/0001-install-ascend.patch
--- a/xllm/compiler/tilelang/patches/tilelang_ascend/0001-install-ascend.patch
+++ b/xllm/compiler/tilelang/patches/tilelang_ascend/0001-install-ascend.patch
@@ -1,4 +1,18 @@
+diff --git a/install_ascend.sh b/install_ascend.sh
+index 48785a9..ed9187c 100644
+--- a/install_ascend.sh
++++ b/install_ascend.sh
+@@ -162,7 +162,7 @@ MAKE_JOBS=$(( CORES * 50 / 100 ))
+ if [ $MAKE_JOBS -lt 1 ]; then
+     MAKE_JOBS=1
+ fi
+-make -j${MAKE_JOBS}
++make -j
+ 
+ if [ $? -ne 0 ]; then
+     echo "Error: TileLang build failed."
 diff --git a/requirements-build.txt b/requirements-build.txt
+index 784cb60..4c2318f 100644
 --- a/requirements-build.txt
 +++ b/requirements-build.txt
 @@ -1,6 +1,5 @@
@@ -8,16 +22,3 @@ diff --git a/requirements-build.txt b/requirements-build.txt
  packaging
  setuptools>=61
  torch
-diff --git a/install_ascend.sh b/install_ascend.sh
---- a/install_ascend.sh
-+++ b/install_ascend.sh
-@@ -140,8 +140,8 @@ echo "Building TileLang with make..."
- # Other wise, make will use all available cores
- # and it may cause the system to be unresponsive
- CORES=$(nproc)
- MAKE_JOBS=$(( CORES * 50 / 100 ))
--make -j${MAKE_JOBS}
-+make -j
-
- if [ $? -ne 0 ]; then
-     echo "Error: TileLang build failed."
